version: 2
updates:
- package-ecosystem: composer
  directory: "/base"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  allow:
  - dependency-type: direct
  - dependency-type: indirect
